  version: '3.8'

  services:
    blog_service:
      build:
        dockerfile: Dockerfile
      working_dir: /app
      command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      tty: true
      stdin_open: true
      ports:
        - "8000:8000"
      volumes:
        - ..:/app
      environment:
        PYTHONPATH: /app
        SECURITY_KEY: "709cb22f047a59f492c4d6407e627240e2272bda11ab791c16fb4f4661f7285a95ba6efbc1bbf762cddcc3710a1487f4a3242f21b2d9cd751b3154a452c5a286"
        ALGORITHM: "HS256"
        ACCESS_TOKEN_EXPIRE_MINUTES: 30
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_HOST: blog_service_db
        POSTGRES_PORT: 5432
        POSTGRES_NAME: blog_db
      depends_on:
        - "blog_service_db"

    blog_service_db:
      image: postgres:13
      restart: always
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: blog_db
      volumes:
        - blog_postgres_data:/var/lib/postgresql/data
      ports:
        - "5433:5432"

  volumes:
    blog_postgres_data:
