[tool.poetry]
name = "tools"
version = "0.1.0"
description = ""
authors = ["Albert Zhemukov <aazhemukov@edu.hse.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
